In [1]:
# Credit Card fraud detection

In [149]:
#importing libraries
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix,classification_report,roc_auc_score
from sklearn.metrics import precision_score,recall_score

In [64]:
#loading CSV file
data=pd.read_csv('creditcard.csv')

In [65]:
#shape of the data
data.shape

(284807, 31)

In [66]:
#about dataset
data.describe()

Time            V1            V2            V3            V4  \
count  284807.000000  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean    94813.859575  1.175161e-15  3.384974e-16 -1.379537e-15  2.094852e-15   
std     47488.145955  1.958696e+00  1.651309e+00  1.516255e+00  1.415869e+00   
min         0.000000 -5.640751e+01 -7.271573e+01 -4.832559e+01 -5.683171e+00   
25%     54201.500000 -9.203734e-01 -5.985499e-01 -8.903648e-01 -8.486401e-01   
50%     84692.000000  1.810880e-02  6.548556e-02  1.798463e-01 -1.984653e-02   
75%    139320.500000  1.315642e+00  8.037239e-01  1.027196e+00  7.433413e-01   
max    172792.000000  2.454930e+00  2.205773e+01  9.382558e+00  1.687534e+01   

                 V5            V6            V7            V8            V9  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   1.021879e-15  1.494498e-15 -5.620335e-16  1.149614e-16 -2.414189e-15   
std    1.380247e+00  1.332271e+00  1.237094e+00  1.194353e+00  1.098632e+00   
min   -1.137433e+02 -2.616051e+01 -4.355724e+01 -7.321672e+01 -1.343407e+01   
25%   -6.915971e-01 -7.682956e-01 -5.540759e-01 -2.086297e-01 -6.430976e-01   
50%   -5.433583e-02 -2.741871e-01  4.010308e-02  2.235804e-02 -5.142873e-02   
75%    6.119264e-01  3.985649e-01  5.704361e-01  3.273459e-01  5.971390e-01   
max    3.480167e+01  7.330163e+01  1.205895e+02  2.000721e+01  1.559499e+01   

       ...           V21           V22           V23           V24  \
count  ...  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05   
mean   ...  1.628620e-16 -3.576577e-16  2.618565e-16  4.473914e-15   
std    ...  7.345240e-01  7.257016e-01  6.244603e-01  6.056471e-01   
min    ... -3.483038e+01 -1.093314e+01 -4.480774e+01 -2.836627e+00   
25%    ... -2.283949e-01 -5.423504e-01 -1.618463e-01 -3.545861e-01   
50%    ... -2.945017e-02  6.781943e-03 -1.119293e-02  4.097606e-02   
75%    ...  1.863772e-01  5.285536e-01  1.476421e-01  4.395266e-01   
max    ...  2.720284e+01  1.050309e+01  2.252841e+01  4.584549e+00   

                V25           V26           V27           V28         Amount  \
count  2.848070e+05  2.848070e+05  2.848070e+05  2.848070e+05  284807.000000   
mean   5.109395e-16  1.686100e-15 -3.661401e-16 -1.227452e-16      88.349619   
std    5.212781e-01  4.822270e-01  4.036325e-01  3.300833e-01     250.120109   
min   -1.029540e+01 -2.604551e+00 -2.256568e+01 -1.543008e+01       0.000000   
25%   -3.171451e-01 -3.269839e-01 -7.083953e-02 -5.295979e-02       5.600000   
50%    1.659350e-02 -5.213911e-02  1.342146e-03  1.124383e-02      22.000000   
75%    3.507156e-01  2.409522e-01  9.104512e-02  7.827995e-02      77.165000   
max    7.519589e+00  3.517346e+00  3.161220e+01  3.384781e+01   25691.160000   

               Class  
count  284807.000000  
mean        0.001727  
std         0.041527  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         0.000000  
max         1.000000  

[8 rows x 31 columns]

In [67]:
#column names
data.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9', 'V10',
       'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19', 'V20',
       'V21', 'V22', 'V23', 'V24', 'V25', 'V26', 'V27', 'V28', 'Amount',
       'Class'],
      dtype='object')

In [68]:
#first 5 records
data.head(5)

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [69]:
#checking fraud and non-fraud based on class column

In [70]:
#records which have non-fraud transcations
data_with_non_fraud=data[data['Class']==0]
data_with_non_fraud.shape

(284315, 31)

In [71]:
#records which have fraud transcations
data_with_fraud=data[data['Class']==1]
data_with_fraud.shape

(492, 31)

In [72]:
#checking if there are any missing values
print(data.isnull().sum())

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64


In [73]:
#checking duplicates in the dataset
print(data.duplicated().sum())

1081


In [84]:
#dropping all the duplicates
data = data.drop_duplicates()
data.shape

(283726, 31)

In [75]:
#checking data types of the data
print(data.dtypes)

Time      float64
V1        float64
V2        float64
V3        float64
V4        float64
V5        float64
V6        float64
V7        float64
V8        float64
V9        float64
V10       float64
V11       float64
V12       float64
V13       float64
V14       float64
V15       float64
V16       float64
V17       float64
V18       float64
V19       float64
V20       float64
V21       float64
V22       float64
V23       float64
V24       float64
V25       float64
V26       float64
V27       float64
V28       float64
Amount    float64
Class       int64
dtype: object


In [93]:
x=data.drop('Class', axis=1)
y=data['Class']

In [94]:
#splitting the whole data into 80% training data and 20% testing data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=40,stratify=y)

In [105]:
#Baseline model selection
#Selected Standard Scaler as the data is uneven(some values are low and some values are high)
#So to make them equal we use StandardScaler
scaler=StandardScaler()

In [106]:
#Fitting model
#Here we have only used x_train as we the test data learns information from the future which is data leakage
scaler.fit(x_train)

StandardScaler()

In [112]:
#Transfrom both training and test data
x_train_scaled_data=scaler.transform(x_train)
x_test_scaled_data=scaler.transform(x_test)

In [116]:
#Model Selection
model=LogisticRegression(class_weight='balanced', random_state=42, max_iter=1000)

In [117]:
#Fitting model
model.fit(x_train_scaled_data,y_train)

LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)

In [121]:
#Predicting
y_pred=model.predict(x_test_scaled_data)
y_pred

array([0, 0, 0, ..., 0, 0, 0], shape=(56746,))

In [124]:
#Confusion mactrix
print(confusion_matrix(y_test, y_pred))

[[55322  1329]
 [   12    83]]


In [125]:
#Classification Report(gives precision, recall, F1-score)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56651
           1       0.06      0.87      0.11        95

    accuracy                           0.98     56746
   macro avg       0.53      0.93      0.55     56746
weighted avg       1.00      0.98      0.99     56746



In [126]:
#ROC-AUC score
print(roc_auc_score(y_test, y_pred))

0.925112391754129


In [141]:
#Probabilities of predictions for threhold tuning
y_pred_proba=model.predict_proba(x_test_scaled_data)[:,1]
y_pred_proba

array([0.06572894, 0.01809878, 0.01165564, ..., 0.02419866, 0.02547205,
       0.04955524], shape=(56746,))

In [147]:
#Threshold tuning
thresholds = [0.50, 0.30, 0.20, 0.10, 0.05]
for t in thresholds:
    print(f'Threshold: {t}') 
    y_pred_t=(y_pred_proba>=t).astype(int)
    #Confusion matrix
    cm = confusion_matrix(y_test, y_pred_t)
    print("Confusion Matrix:\n", cm)
    #precision 
    precision = precision_score(y_test, y_pred_t)
    print('Precision:', precision)
    #recall
    recall = recall_score(y_test, y_pred_t)
    print('Recall: ', recall)

Threshold: 0.5
Confusion Matrix:
 [[55322  1329]
 [   12    83]]
Precision: 0.058781869688385266
Recall:  0.8736842105263158
Threshold: 0.3
Confusion Matrix:
 [[53656  2995]
 [    8    87]]
Precision: 0.028228423101881894
Recall:  0.9157894736842105
Threshold: 0.2
Confusion Matrix:
 [[51494  5157]
 [    7    88]]
Precision: 0.016777883698760723
Recall:  0.9263157894736842
Threshold: 0.1
Confusion Matrix:
 [[45453 11198]
 [    5    90]]
Precision: 0.007973068745570517
Recall:  0.9473684210526315
Threshold: 0.05
Confusion Matrix:
 [[36153 20498]
 [    3    92]]
Precision: 0.004468188440990772
Recall:  0.968421052631579


In [157]:
#Here from above, for threshold 0.05, recall is 0.96, it means 96% catches fraud
#Best threshold value now
low_thresholds = np.arange(0.001, 0.11, 0.001)
#finding best recall
best_recall=0
best_threshold=None
best_cm=None
for t in low_thresholds:
    y_pred_t=(y_pred_proba>=t).astype(int)
    #Confusion matrix
    cm = confusion_matrix(y_test, y_pred_t)
    #precision 
    precision = precision_score(y_test, y_pred_t)
    #recall
    recall = recall_score(y_test, y_pred_t)
    if recall>best_recall:
        best_recall=recall
        best_threshold=t
        best_cm=cm = confusion_matrix(y_test, y_pred_t)

print("Best Threshold for max Recall:", best_threshold)
print("Highest Recall:", best_recall)
print("Confusion Matrix at Best Threshold:\n", best_cm)   

Best Threshold for max Recall: 0.001
Highest Recall: 1.0
Confusion Matrix at Best Threshold:
 [[ 3676 52975]
 [    0    95]]
